---
- name: Install Java 1.7 and some basic dependencies (yum)
  yum: name={{ item }} state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'    
  with_items:
   - unzip
   - java-1.7.0-openjdk
   
- name: Install Java 1.7 and some basic dependencies (apt)
  apt: pkg={{ item }} state=present update_cache=yes  
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'  
  with_items:
   - unzip
   - openjdk-7-jdk

- name: Create directory for Jboss build
  file: path=/opt/ state=directory mode=0755
    
- name: Download JBoss from jboss.org
  get_url: url={{ jboss_url }} dest=/opt/{{ jboss_archive }}

- name: Extract archive
  command: chdir=/usr/share /usr/bin/unzip -q /opt/{{ jboss_archive }} creates={{ jboss_base_dir }}

  # Rcd /g the version in the init script
- name: Rename install directory
  command: chdir=/usr/share /bin/mv {{ jboss_archive_extracted }} jboss-as creates={{ jboss_base_dir }}

- name: Copying standalone.xml configuration file
  template: src=standalone.xml dest={{ jboss_base_dir }}/standalone/configuration/
  notify: restart jboss

- name: Add group "{{ jboss_group }}"
  group: name={{ jboss_group }}

- name: Add user "{{ jboss_owner }}"
  user: name={{ jboss_owner }} group=jboss home={{ jboss_base_dir }} comment="Jboss User" 

- name: Change ownership of JBoss installation
  file: path={{ jboss_base_dir }}/ owner={{ jboss_owner }} group={{ jboss_group }} shell={{ jboss_shell }} state=directory recurse=yes

- name: Copy the init script
  copy: src=jboss-as-standalone-{{ ansible_distribution }}-{{ ansible_architecture }}.sh dest=/etc/init.d/jboss mode=0755

- name: Enable JBoss to be started at boot
  service: name=jboss enabled=yes state=started 

#- name: deploy iptables rules
#  template: src=iptables-save dest=/etc/sysconfig/iptables
#  notify: restart iptables
